\c items_dev;
-- owner,
INSERT INTO items (name, image, cost, quantity, category, description, email) VALUES 
('The Legend of Zelda Tears of the Kingdom',
'https://gonintendo.com/attachments/image/13494/file/medium-fbddf65cf91a8779f5114438f71b8539.jpg', 
'69.99', 
'700', 
'games',
'Tears of the Kingdom retains the open-world action-adventure gameplay of the prior game, Breath of the Wild (2017). As Link, players explore Hyrule and two new areas, the Sky Islands and the Depths, to find weapons, resources, and complete quests.',
'keeanurodriguez@pursuit.org'),
('Iphone 12',
'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIActBYpKmqeSZ2-inP3eF30nafRFpGjk9xLWBlD3Adg&usqp=CAU&ec=48600113', 
'799.99', 
'100', 
'tech',
'The iPhone 12 features a 6.1-inch (155 mm) display with Super Retina XDR OLED technology at a resolution of 2532 x 1170 pixels and a pixel density of about 460 ppi.',
'keeanurodriguez@pursuit.org'),
('T-shirt',
'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTquMUcJDpk-lDJzt2rgLJ1Gn6k-_xOv09Ya2u-8jRbDQ&usqp=CAU&ec=48600113',
'24.99',
'20',
'clothes',
'T-shirt that says I love NYC',
'keeanurodriguez@pursuit.org'),
('Dress',
'https://m.media-amazon.com/images/I/51tsoAUQ2HL._AC_UX679_.jpg',
'89.99',
'10',
'clothes',
'A dress for young women',
'keeanurodriguez@pursuit.org'),
('T-rex',
'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6502/6502888_sd.jpg;maxHeight=640;maxWidth=550',
'39.99',
'50',
'toys',
'A plastic t-rex action figure',
'keeanurodriguez@pursuit.org'),
('Headphones',
'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4505/4505300_sd.jpg;maxHeight=640;maxWidth=550',
'69.99',
'5',
'tech',
'The HyperX Cloud II was built to be an ultra-comfortable gaming headset with amazing sound. We put a lot of thought into the details of our HyperX signature memory foam, the premium leatherette, clamping force, and weight distribution to create a headset that’s comfortable through long gaming sessions. It’s no wonder that it’s become the preferred gaming headset for millions of gamers. Whether you want to focus on the competition or relax with some of your favorite games, there’s a Cloud that’s perfect for you.',
'keeanurodriguez@pursuit.org'),
('Hat',
'https://www.ikea.com/us/en/images/products/knorva-hat-blue__0812162_pe771942_s5.jpg',
'5.99',
'60',
'clothes',
'This hat is made of the same durable materials as one of the worlds most used bags. Provides protection from the sun and rain, and is easy to keep clean, just rinse and dry.',
'keeanurodriguez@pursuit.org'),
('Cooking Set',
'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTactVGv6NAVBPOu5AjA1MkFGWZk0aECImKhy-2oREMNP4omhzDY23Ut7_GPIXYHEgYd8v1qQeuwZqrVHQiiXPJec7nXWa5C6UCtwszUw6HbWC-fWRiIZeOihbyp3d9emyTdTM&usqp=CAc',
'28.20',
'2',
'toys',
'A 40 piece cooking set for young girls',
'keeanurodriguez@pursuit.org'),
('Elden Ring',
'https://media.gamestop.com/i/gamestop/11172342/Elden-Ring---PC-Steam?$pdp2x$',
'59.99',
'1000',
'games',
'Danger lurks in every corner in Elden Ring on PC Steam. Explore an open world rich with magic, ruins, and combat. Encounter the game’s secrets as you discover its mysteries. The Golden Order has been broken. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the lands between.',
'keeanurodriguez@pursuit.org'),
('Doom Eternal',
'https://upload.wikimedia.org/wikipedia/en/9/9d/Cover_Art_of_Doom_Eternal.png',
'59.99',
'800',
'games',
'Experience the ultimate combination of speed and power with the next leap in push-forward, first-person combat, As the DOOM Slayer, return to take your vengeance against the forces of Hell',
'keeanurodriguez@pursuit.org'),
('Boys Overall',
'https://m.media-amazon.com/images/I/91pAEhWrO+L._AC_UY879_.jpg',
'20.00',
'34',
'clothes',
'ADJUSTABLE FIT. Built with adjustable shoulder straps, these overalls are designed to suit your little boys needs by helping him get his perfect fit, even as he grows.',
'keeanurodriguez@pursuit.org'),
('Macbook Air', 
'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKWKzs2BmJwAsAZoqH78wqFh93-jvxZPAl23f92LJdtQ&usqp=CAU&ec=48600113', 
'999.99', 
'1', 
'tech',
'The MacBook Air is a line of laptop computers developed and manufactured by Apple since 2008. It features a thin, light structure in a machined aluminum case and a 13-inch screen.',
'keeanurodriguez@pursuit.org');

-- INSERT INTO cart (item_id, total) VALUES 
-- ('1'),
-- ('1'),
-- ('2');